repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key
      - id: no-commit-to-branch
        args: ['--branch', 'main']

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.40.0
    hooks:
      - id: eslint
        files: \.(js|ts|tsx)$
        types: [file]
        additional_dependencies:
          - eslint@9.23.0
          - typescript@5.8.2
          - '@typescript-eslint/eslint-plugin@8.28.0'
          - '@typescript-eslint/parser@8.28.0'

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.9-for-vscode
    hooks:
      - id: prettier
        files: \.(js|jsx|ts|tsx)$
        types: [file]

  - repo: local
    hooks:
      - id: check-env-vars
        name: Check for hardcoded environment variables
        entry: bash -c 'grep -r "EXPO_PUBLIC_SUPABASE_URL\|EXPO_PUBLIC_SUPABASE_ANON_KEY" --include="*.ts" --include="*.tsx" --exclude="env.ts" app/ && exit 1 || exit 0'
        language: system
        types: [file]
        exclude: '.env.example'

      - id: ts-check
        name: TypeScript Check
        entry: npx tsc --noEmit
        language: system
        types: [file]
        files: \.(ts|tsx)$
        pass_filenames: false
