name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  lint-and-typecheck:
    name: Lint and Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run TypeScript check
        run: npm run tsc

      - name: Check for console.log statements
        run: |
          if grep -r "console\.log" --include="*.ts" --include="*.tsx" ./app/; then
            echo "⚠️ Warning: console.log statements found. Consider removing them before deploying to production."
          else
            echo "✅ No console.log statements found."
          fi

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: |
          # If you have tests, uncomment the line below
          # npm test
          echo "No tests configured yet. Consider adding tests for production readiness."

  build-preview:
    name: Build Preview
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: [lint-and-typecheck, test]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Verify Expo CLI
        run: npx expo --version

      - name: Build preview bundle
        run: |
          npx expo export --dump-sourcemap --dev --clear

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: expo-web-build
          path: dist/
          retention-days: 3
